# Generated by Django 4.1 on 2022-12-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_ID', models.CharField(max_length=255, unique=True)),
                ('college_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('year_founded', models.DateField()),
                ('accreditation', models.DateField()),
                ('building_ID_initial', models.CharField(max_length=255)),
                ('user_ID_initial', models.CharField(max_length=255)),
            ],
        ),
    ]
