# Generated by Django 4.1 on 2022-12-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAPI', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
