# Generated by Django 4.1 on 2022-12-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeAPI', '0005_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.ImageField(upload_to='citizenship_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
